### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by sm2x** [Sorunome/matrix-synchrotron-balancer#3]
OS:  Ubuntu 18.04
Golang:  go1.10.4 linux/amd64  (installed using # apt install golang)

I followed the instruction, git the repo, cd to matrix-synapse-balancer
go build throws:
main.go:18:2: cannot find package "github.com/Sorunome/matrix-synchrotron-balancer/config" in any of:
	/usr/lib/go-1.10/src/github.com/Sorunome/matrix-synchrotron-balancer/config (from $GOROOT)
	/root/go/src/github.com/Sorunome/matrix-synchrotron-balancer/config (from $GOPATH)
main.go:16:2: cannot find package "github.com/struCoder/pidusage" in any of:
	/usr/lib/go-1.10/src/github.com/struCoder/pidusage (from $GOROOT)
	/root/go/src/github.com/struCoder/pidusage (from $GOPATH)

**Comment by Sorunome** [comment]
Since soru dosen't know too much on this, she'll quote @tulir 

> outdated go version
> might still work with go get, but just using up to date software is easier

**Comment by sm2x** [comment]
got it working, thanks for your reply, im new to matrix synapse but got a successful installation nevertheless, what I can not figure out is the pid_file of syncros, where do you define the location of synchrotrons' pid files?

**Comment by Sorunome** [comment]
You will have to set up your system to generate the pid files. As there are multiple ways to generate pid files for tasks you started and it is highly dependent on your setup, that part is not covered here.

**Comment by sm2x** [comment]
but is pid_files mandatory on balancer config.yaml?

**Comment by Sorunome** [comment]
Yes. It is used to determine the loads of the synchrotrons and thus determine where to redirect requests to

**Comment by sm2x** [comment]
thank you, will figure out

**Comment by vaibhavgupta16** [comment]
@sm2x I'm also getting the package not found error. Could you tell me how did you solve it ?

**Comment by sm2x** [comment]
> @sm2x I'm also getting the package not found error. Could you tell me how did you solve it ?

abandoned using this solution, you can accomplish this through matrix itself
